name: Push Starter Code to Public Repo
on:
  push:
    branches:
      - main
jobs:
  push_starter_code:
    # run job only if commit message matches PA-*/starter_code
    if: |
      contains(github.event.head_commit.message, 'starter_code') && 
      github.event.head_commit.message =~ '^PA-[^/]+/starter_code$'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Extract PA Directory from commit message
        id: extract_pa_dir
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" =~ ^(PA-[^/]+)/starter_code$ ]]; then
            PA_DIR="${BASH_REMATCH[1]}"
            echo "Extracted PA directory: $PA_DIR"
            echo "pa_dir=$PA_DIR" >> $GITHUB_ENV
          else
            echo "Invalid commit message format. Expected format: PA-*/starter_code."
            exit 1
          fi
      - name: Run Make in PA Directory
        run: |
          if [ -z "${{ env.pa_dir }}" ]; then
            echo "No PA directory found. Skipping make."
            exit 1
          fi
          echo "Running make in ${{ env.pa_dir }}"
          (cd "${{ env.pa_dir }}" && make)
      - name: Push Starter Code to Public Repo
        run: |
          git config --global user.name "action"
          git config --global user.email "action@github.com"
          echo "${{ secrets.DEPLOY_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add private_key.pem
          PUBLIC_REPO="git@github.com:rkulskis/autograder-template-starter-code.git"
          TEMP_DIR=$(mktemp -d)
          git clone "$PUBLIC_REPO" "$TEMP_DIR"
          if [ -d "${{ env.pa_dir }}/starter_code" ]; then
          mkdir -p "$TEMP_DIR/${{ env.pa_dir }}"
          cp -r "${{ env.pa_dir }}/starter_code/." "$TEMP_DIR/${{ env.pa_dir }}/"
          fi
          cd "$TEMP_DIR"
          git add .
          if git diff-index --quiet HEAD; then
          echo "No changes to push."
          else
          git commit -m "Update starter code for ${{
          env.pa_dir }}/starter_code"
          git push origin main
          fi
